# Generated by Django 6.0.3 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="steps_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
