# Generated by Django 6.0.3 on 2026-03-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generation', '0002_add_steps_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='screenshots_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
