# Generated by Django 6.0.3 on 2026-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='failure_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='failure_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
