# Generated by Django 6.0.3 on 2026-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_runner', '0002_testrun_failure_summary_testrun_failure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
