# Generated by Django 6.0.3 on 2026-03-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_generation', '0002_add_steps_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', max_length=50)),
                ('framework', models.CharField(default='playwright_sync', max_length=50)),
                ('script_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_generation.testcase')),
            ],
        ),
    ]
